<?php
/** Define Constant **/
define('DATABASE_MS_ACCESS_PATH_FILE','/APEX/Python_APEX/3_WISE_SOL_PROJECT/Database/HWSD.mdb');
define('PYTHON_APEX_MODEL','/APEX/Python_APEX/');
define('APEX_MODEL','');
/** Admin Tool APEX Projecrt **/
define('APEX_ADMIN_TOOL', 'admin/APEX');
define('APEX_ADMIN_TOOL_VIEW_DATA', 'admin/APEX/View_Data');
define('APEX_ADMIN_TOOL_VIEW_DATA_INSERT_FROM_MOBILE_LANDPKS','admin/APEX/View_Data/LandPKS_InputData_From_Mobile');
define('APEX_ADMIN_TOOL_RUN_PYTHON_APEX', 'admin/APEX/Run_Python_Model');
/** APEX Project Internal Genrate System **/
define('APEX_APIS_INSERT_DATA_FROM_MOBILE','SiteAnalysis');
define('APEX_APIS_REQUEST_GDAL_DATA','GDALInformation');
define('APEX_APIS_REQUEST_RHM_DATA','RHMInformation');
define('APEX_APIS_REQUEST_LANDPKS_DATA','LandPKSInformation');
define('APEX_APIS_INSERT_DATA_FROM_MOBILE_RHM','RHMSummary');
define('APEX_FORM_REQUEST_EXPORT_INPUT_DATA','admin/APEX/View_Data/data_export');
define('APEX_FORM_REQUEST_EXPORT_INPUT_DATA_RESULT','admin/APEX/View_Data/data_export/result/%/%');
/** Using to Test Server **/
define('APEX_APIS_TEST_SERVER','TestServer');
/** Shiny Server connection **/
define('URL_SHINY_RHM_CHARTS','https://landpotential.shinyapps.io/RHMcharts/?');

/** Consider Folder containing CSV Export **/
define('FOLDER_PATH_CSV_EXPORT','sites/default/public_shiny_csv/');


?>